/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sawanna;

import javax.swing.JOptionPane;

/**
 *
 * @author Bartosz Radliński
 */
public class SetUp extends javax.swing.JFrame {

    /**
     * Creates new form SetUp
     */
    public SetUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WorldBuilderPanel = new javax.swing.JPanel();
        WaterPlaceButton = new javax.swing.JButton();
        RockButton = new javax.swing.JButton();
        EleRockButton = new javax.swing.JButton();
        TreeButton = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();
        ConfirmButton = new javax.swing.JButton();
        AnimalCreatorPanel = new javax.swing.JPanel();
        GnuButton = new javax.swing.JButton();
        LionButton = new javax.swing.JButton();
        HyenaButton = new javax.swing.JButton();
        BirdButton = new javax.swing.JButton();
        SnakeButton = new javax.swing.JButton();
        WorldEditButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        CarrionButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setMaximumSize(new java.awt.Dimension(250, 350));
        setMinimumSize(new java.awt.Dimension(250, 350));
        setPreferredSize(new java.awt.Dimension(250, 350));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        WaterPlaceButton.setText("Wodopój");
        WaterPlaceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WaterPlaceButtonActionPerformed(evt);
            }
        });

        RockButton.setText("Lwia Skała");
        RockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RockButtonActionPerformed(evt);
            }
        });

        EleRockButton.setText("Cmentarzysko");
        EleRockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EleRockButtonActionPerformed(evt);
            }
        });

        TreeButton.setText("Drzewa");
        TreeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TreeButtonActionPerformed(evt);
            }
        });

        ClearButton.setText("Usuń");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        ConfirmButton.setText("Ok");
        ConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout WorldBuilderPanelLayout = new javax.swing.GroupLayout(WorldBuilderPanel);
        WorldBuilderPanel.setLayout(WorldBuilderPanelLayout);
        WorldBuilderPanelLayout.setHorizontalGroup(
            WorldBuilderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WorldBuilderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(WorldBuilderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(WaterPlaceButton)
                    .addComponent(RockButton)
                    .addComponent(EleRockButton)
                    .addComponent(TreeButton)
                    .addComponent(ClearButton)
                    .addComponent(ConfirmButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        WorldBuilderPanelLayout.setVerticalGroup(
            WorldBuilderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WorldBuilderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(WaterPlaceButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RockButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EleRockButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TreeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ClearButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ConfirmButton)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        GnuButton.setText("Antylopa");
        GnuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GnuButtonActionPerformed(evt);
            }
        });

        LionButton.setText("Lew");
        LionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LionButtonActionPerformed(evt);
            }
        });

        HyenaButton.setText("Hiena");
        HyenaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HyenaButtonActionPerformed(evt);
            }
        });

        BirdButton.setText("Ptak");
        BirdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BirdButtonActionPerformed(evt);
            }
        });

        SnakeButton.setText("Wąż");
        SnakeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SnakeButtonActionPerformed(evt);
            }
        });

        WorldEditButton.setText("Edytuj świat");
        WorldEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WorldEditButtonActionPerformed(evt);
            }
        });

        CancelButton.setText("Anuluj");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        CarrionButton.setText("Padlina");
        CarrionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarrionButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AnimalCreatorPanelLayout = new javax.swing.GroupLayout(AnimalCreatorPanel);
        AnimalCreatorPanel.setLayout(AnimalCreatorPanelLayout);
        AnimalCreatorPanelLayout.setHorizontalGroup(
            AnimalCreatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AnimalCreatorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AnimalCreatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AnimalCreatorPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(AnimalCreatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GnuButton)
                            .addComponent(LionButton)
                            .addComponent(HyenaButton)
                            .addComponent(BirdButton)
                            .addComponent(SnakeButton)
                            .addComponent(WorldEditButton)))
                    .addGroup(AnimalCreatorPanelLayout.createSequentialGroup()
                        .addGroup(AnimalCreatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CancelButton)
                            .addComponent(CarrionButton))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        AnimalCreatorPanelLayout.setVerticalGroup(
            AnimalCreatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AnimalCreatorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GnuButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LionButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HyenaButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BirdButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SnakeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CarrionButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(WorldEditButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CancelButton)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(WorldBuilderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AnimalCreatorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(635, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AnimalCreatorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WorldBuilderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 214, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Ustalenie stanu usuwania pól podłoża
     */
    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed

        Board.setWorldBuildState(5);
    }//GEN-LAST:event_ClearButtonActionPerformed

    /**
     * Ustalanie domyślnych wartości stanów
     */
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        WorldBuilderPanel.setVisible(true);
        Board.setBoardState(0);
        Board.setPatrolAniType(null);

        Board.setWorldBuildState(0);
        Board.setAnimalCreatorState(0);
        AnimalCreatorPanel.setVisible(false);
    }//GEN-LAST:event_formWindowOpened
    /**
     * Ustalenie stanu tworznie wodopoju
     */
    private void WaterPlaceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WaterPlaceButtonActionPerformed

        Board.setWorldBuildState(1);
    }//GEN-LAST:event_WaterPlaceButtonActionPerformed
    /**
     * Ustalenie stanu tworzenia lwiej skały
     */
    private void RockButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RockButtonActionPerformed

        Board.setWorldBuildState(2);
    }//GEN-LAST:event_RockButtonActionPerformed
    /**
     * Ustalanie stanu tworzenia Cmentarzyska słoń
     */
    private void EleRockButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EleRockButtonActionPerformed

        Board.setWorldBuildState(3);
    }//GEN-LAST:event_EleRockButtonActionPerformed
    /**
     * Ustalanie stanu tworzenia drzew
     */
    private void TreeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TreeButtonActionPerformed

        Board.setWorldBuildState(4);
    }//GEN-LAST:event_TreeButtonActionPerformed
    /**
     * Przejście do okna kreacji zwierząt; Jeżeli brak wody - sygnalizacja
     */
    private void ConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmButtonActionPerformed
        boolean watter = false;
        for (int i = 0; i < ISettings.WORKSPACE_POINTS_X; i++) {
            for (int j = 0; j < ISettings.WORKSPACE_POINTS_X; j++) {
                if (Board.getStatic_fields(i, j).getSpriteName().equals(ISettings.WATER)) {
                    watter = true;
                }
            }
        }
        if (watter) {
            WorldBuilderPanel.setVisible(false);
            Board.setPatrolAniType(null);
            Board.setWorldBuildState(0);

            Board.setBoardState(1);

            Board.setAnimalCreatorState(0);
            AnimalCreatorPanel.setAlignmentX(0);
            AnimalCreatorPanel.setAlignmentY(0);
            AnimalCreatorPanel.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this,
                    "Hmm..., bez wody będzie ciężko ...",
                    "ERROR",
                    JOptionPane.ERROR_MESSAGE);
            Board.setLastWaterPoint(null);
        }
    }//GEN-LAST:event_ConfirmButtonActionPerformed
    /**
     * Pwrót do edycji świata
     */
    private void WorldEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WorldEditButtonActionPerformed
        WorldBuilderPanel.setAlignmentX(0);
        WorldBuilderPanel.setAlignmentY(0);
        WorldBuilderPanel.setVisible(true);
        Board.setBoardState(0);
        Board.setPatrolAniType(null);

        Board.setWorldBuildState(0);
        Board.setAnimalCreatorState(0);


        AnimalCreatorPanel.setVisible(false);
    }//GEN-LAST:event_WorldEditButtonActionPerformed
    /**
     * Ustalanie stanu tworzenia antylop
     */
    private void GnuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GnuButtonActionPerformed

        Board.setAnimalCreatorState(1);
    }//GEN-LAST:event_GnuButtonActionPerformed
    /**
     * Anulowanie tworzenia zwierząt
     */
    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed

        Board.setAnimalCreatorState(0);
    }//GEN-LAST:event_CancelButtonActionPerformed
    /**
     * Ustalanie stanu tworzenia lwów
     */
    private void LionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LionButtonActionPerformed

        Board.setAnimalCreatorState(2);
    }//GEN-LAST:event_LionButtonActionPerformed
    /**
     * Ustalanie stanu tworzenia padliny
     */
    private void CarrionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarrionButtonActionPerformed

        Board.setAnimalCreatorState(6);
    }//GEN-LAST:event_CarrionButtonActionPerformed
    /**
     * Ustalanie stanu tworzenia hien
     */
    private void HyenaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HyenaButtonActionPerformed

        Board.setAnimalCreatorState(3);
    }//GEN-LAST:event_HyenaButtonActionPerformed
    /**
     * Ustalanie stanu tworzenia ptaków
     */
    private void BirdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BirdButtonActionPerformed

        Board.setAnimalCreatorState(4);
    }//GEN-LAST:event_BirdButtonActionPerformed
    /**
     * Ustalanie stanu tworzenia węży
     */
    private void SnakeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SnakeButtonActionPerformed

        Board.setAnimalCreatorState(5);
    }//GEN-LAST:event_SnakeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SetUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SetUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SetUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SetUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SetUp().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AnimalCreatorPanel;
    private javax.swing.JButton BirdButton;
    private javax.swing.JButton CancelButton;
    private javax.swing.JButton CarrionButton;
    private javax.swing.JButton ClearButton;
    private javax.swing.JButton ConfirmButton;
    private javax.swing.JButton EleRockButton;
    private javax.swing.JButton GnuButton;
    private javax.swing.JButton HyenaButton;
    private javax.swing.JButton LionButton;
    private javax.swing.JButton RockButton;
    private javax.swing.JButton SnakeButton;
    private javax.swing.JButton TreeButton;
    private javax.swing.JButton WaterPlaceButton;
    private javax.swing.JPanel WorldBuilderPanel;
    private javax.swing.JButton WorldEditButton;
    // End of variables declaration//GEN-END:variables
}
